rework: remove github issue to follow request status

diff --git a/.github/workflows/plan_callback.yaml b/.github/workflows/plan_callback.yaml
--- a/.github/workflows/plan_callback.yaml
+++ b/.github/workflows/plan_callback.yaml
@@ -1,9 +1,9 @@
-name: Plan callback
+name: Review plan for apply execution
 on:
   workflow_dispatch:
     inputs:
-      request_id:
-        description: Request ID (for now, issue number)
+      backend_prefix:
+        description: Prefix in the object storage containing the backend state files
         type: string
         required: true
       status:
@@ -14,17 +14,21 @@ on:
         description: Run ID of the caller (concatenation of run_id and run_attempt)
         type: string
         required: true
+      environment:
+        description: Factory environment
+        type: string
+        required: true
       tf_plan_summary:
         description: TF plan summary
+        type: string
+      callback_repo:
+        type: string
+      callback_workflow:
         type: string
 
 permissions:
   contents: read
-  issues: write
-
-concurrency:
-  group: request-${{ inputs.request_id }}
-  cancel-in-progress: false
+  actions: write
 
 jobs:
   plan_callback:
@@ -32,45 +36,59 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.12"
-
-      - name: Install dependencies
-        run: pip install PyGithub
-
-      - name: Apply state transition
-        env:
-          REQUEST_ID: ${{ inputs.request_id }}
-          TARGET_STATUS: ${{ inputs.status }}   # "PLAN_SUCCESS", "PLAN_FAILED" or "NO_CHANGES"
-          STORE_BACKEND: github
-          REQUEST_REPO: ${{ github.repository }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: python3 scripts/transition_guard.py transition
-
-      - name: Update request with plan summary
+      - name: Display the terraform summary within the workflow summary
         if: inputs.status == "PLAN_SUCCESS" && ${{ inputs.tf_plan_summary }}
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          TF_PLAN_SUMMARY: ${{ inputs.tf_plan_summary }}
-          PLAN_RUN_ID: ${{ inputs.run_id }}
+          SUMMARY: ${{ inputs.tf_plan_summary }}
         run: |
-          echo 'tf plan summary received:'
-          echo "$TF_PLAN_SUMMARY"
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
 
-          ISSUE_COMMENT="$TF_PLAN_SUMMARY"
-          ISSUE_COMMENT+='
-          To launch apply execution, add a comment with `/approve-deployment ${{ inputs.run_id }}`
-          (temporary solution, in corp. environment, use Github environment reviewers)'
 
-          gh issue comment ${{ inputs.request_id }} --body "$ISSUE_COMMENT"
-
-      - name: Close issue on no-op plan
-        if: inputs.status == 'NO_CHANGES'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  apply_execution:
+    runs-on: ubuntu-latest
+    needs: plan_callback
+    # The environment attached to this job MUST require approval before the job can proceed.
+    # TODO: determine whether the environment is hard coded at the service catalog level or if it should be provided somehow
+    environment: manual-approval
+    steps:
+      - name: Create a workflow run for the terraform apply execution
+        if: inputs.status == "PLAN_SUCCESS" && ${{ inputs.tf_plan_summary }}
         run: |
-          gh issue comment ${{ inputs.request_id }} \
-            --body "Terraform plan detected no changes. Infrastructure is already up to date. Closing request."
-          gh issue close ${{ inputs.request_id }} --reason "not planned"
+          echo "Triggering terraform apply workflow..."
+          RUN_ID=$(echo "${{ inputs.run_id }}" | tr -d '[:space:]' | grep -oE '[0-9]+-[0-9]+$') || echo "::error::run_id format error."
+
+          if [ -z "$RUN_ID" ]; then
+            echo "::error::Expected format: '<digits>-<digits>' at end of line."
+            exit 1
+          fi
+
+          cat <<-EOF > request_body.json
+          {
+            "ref":"main",
+            "inputs":{
+              "backend_prefix": "${{ inputs.backend_prefix }}",
+              "plan_run_id":"${{ inputs.run_id }}",
+              "environment": "${{ inputs.environment }}",
+              "callback_repo": "${{ github.repository }}",
+              "callback_workflow": "apply_callback.yaml"
+            }
+          }
+          EOF
+
+          echo 'request_body.json content:'
+          cat request_body.json
+
+          # TODO: use installation access token instead of PAT (must have Action (write) permission on called repo)
+          HTTP_STATUS=$(curl -w "%{http_code}" -s -o response.json \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.PAT }}" \
+            -H "X-GitHub-Api-Version: 2026-03-10" \
+            https://api.github.com/repos/${{ inputs.callback_repo }}/actions/workflows/${{ inputs.callback_workflow }}/dispatches \
+            -d @request_body.json)
+
+          if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 300 ]; then
+            echo "::error::GitHub API call failed with status $HTTP_STATUS"
+            cat response.json
+            exit 1
+          fi
